### ISSUE TITLE
[kernel][x86] Multiple checks in isr_handler

### ISSUE THREAD

**Issue by Supercip971** [opuntiaOS-Project/opuntiaOS#39]
https://github.com/opuntiaOS-Project/opuntiaOS/blob/58eeddecd6f3f83a7fecd10dd4a3f67e038348da/kernel/kernel/platform/x86/interrupts/isr_handler.c#L105

why not use:
```c
if(i != 0 && i != 6 && i != 14)
```
instead of using 13 else if with the same action inside ?

(can't do a pr as I can't build the toolchain (https://github.com/opuntiaOS-Project/opuntiaOS/issues/37) )

**Comment by Abb1x** [comment]
also pls use `switch`

**Comment by nimelehin** [comment]
@Supercip971 If you want to create a pr, for a temporary solution you can use LLVM Toolchain.

**Comment by bellrise** [comment]
Fixed this on my fork, will be turned into a PR soon.
