### ISSUE TITLE
Mobile Tracker Free

### ISSUE THREAD

**Issue by Ride-robiSantw** [opuntiaOS-Project/opuntiaOS#54]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Please share data from out/base/boot/kernel.config**
<details><summary>Kernel Config</summary>
Paste here
</details>

**Please share a stack trace**
<details><summary>Trace</summary>
Paste here
</details>

**Additional context**

**Comment by Ride-robiSantw** [comment]
out/base/boot/kernel.config

**Comment by nimelehin** [comment]
Hey! Thanks for opening the issue here!

Could you please clarify the issue with `out/base/boot/kernel.config` you want to describe? 
Thanks.

**Comment by nimelehin** [comment]
Closing for now. If you have any information feel free to reopen the issue
