### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by XSSpark** [opuntiaOS-Project/opuntiaOS#58]
Hi, 

I am facing this error when I try to compile : 

`$ ./all.sh`
`[112/372] ASM obj/kernel/kernel/platform/x86/base/boot/kernel.bin.registers_helper.o`
`FAILED: obj/kernel/kernel/platform/x86/base/boot/kernel.bin.registers_helper.o`
`nasm  ../kernel/kernel/platform/x86/registers_helper.s -o obj/kernel/kernel/platform/x86/base/boot/kernel.bin.registers_helper.o -f elf
../kernel/kernel/platform/x86/registers_helper.s:2: error: symbol 'read_ip' redefined`
`[121/372] CC obj/kernel/kernel/mem/base/boot/kernel.bin.vmm.o`
`ninja: build stopped: subcommand failed.`
`[ERROR] Can't build for arch: x86`
`[ERROR] All command failed`

I have tried with LLVM & gnu toolchain. (Followed step by step [opuntiaOS's Build Note](https://github.com/opuntiaOS-Project/opuntiaOS/blob/master/docs/build.md))

Do you have an idea about that ? 

Thanks

**Comment by nimelehin** [comment]
Hey, this should be fixed in master now. Thanks for reporting!
