### ISSUE TITLE
[kernel] Wrong month in Time Manager

### ISSUE THREAD

**Issue by XSSpark** [opuntiaOS-Project/opuntiaOS#59]
Hi

Correct me if i'm wrong 

This `31 + 28 + 31 + 30 + 31 + 31 + 30 + 31 + 30 + 31 + 30 + 31` represents months, right? 

So if yes, it should be `31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 + 30 + 31 + 30 + 31` right (from L28 to L34)? 

https://github.com/opuntiaOS-Project/opuntiaOS/blob/abc7289d02acb6cca6688860bf8f7d48e9f1a9b4/kernel/kernel/time/time_manager.c#L21-L35

Regards

**Comment by nimelehin** [comment]
Hey, yeah, looks like you are right.
